# Generated by Django 2.2.1 on 2019-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thevotingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='imagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
